### ISSUE TITLE
Recovery flow: email address stays filled in the code field

### ISSUE THREAD

**Issue by hyperknot** [ory/elements#78] opened 2023-01-19 13:42 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/elements/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/elements/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

After sending the email in the recovery flow, the email stays filled in the UI, in the code field.

I think people would be quite confused about this, not realising that they need to delete the email address first and then copy-paste the code.

### Reproducing the bug

Run the next.js example, do the recovery.

### Version

master

**Comment by meotimdihia** [comment] 2023-02-12 20:15
I got this problem too.

**Comment by francesconi** [comment] 2023-10-03 19:05
Any updates on the pull requests?

**Comment by zepatrik** [comment] 2023-10-10 16:00
I cannot reproduce this anymore, is this already fixed on the latest version? I used the next.js SPA example and recovery just worked as expected.

**Comment by Benehiko** [comment] 2023-10-10 16:03
I think this might be related to when you use the returned payload from `recovery` to populate the fields. I've updated the examples to avoid this and re-fetch the flow data a while back. 

 https://github.com/ory/elements/commit/85cc97964328ff44488d10b35e385c070f2b2f5f#diff-88bbaecc97b612f9578a168dd4f2749e93c0844283f8c4f58736dc880a2b1e1f

**Comment by zepatrik** [comment] 2023-10-10 16:04
Checking on a customer's deployed UI that has the issue, it appears that the same ID is used for the input field, which makes react not re-render the field and keeps the wrong content. I guess we can easily fix this by constructing a unique ID.

**Closed** 2023-10-11 07:35 UTC
Labels: bug
